import { z } from 'zod';
import { defaultReservation, changeReservation, reservationDocument, reservationReply, availableTimes, seatingOptions } from '../public/restaurant/booking.js';
import { validateDocument } from './protocol.ts';
const preferences={cuisine:z.enum(['italian','japanese','mexican']),day:z.enum(['tonight','tomorrow','weekend']),party:z.enum(['1','2','3','4','5','6','7','8']),seating:z.enum(['indoor','patio']),time:z.enum(['','17:30','18:00','18:30','19:00','19:30','20:00'])};
export const restaurantSchema=z.object({...preferences,stage:z.enum(['choose','review','confirmed'])}).strict().refine(s=>Object.keys(seatingOptions(s)).includes(s.seating)&&(s.stage==='choose'?s.time==='':availableTimes(s).includes(s.time)));
const replySchema=z.object({patch:z.object(preferences).partial().extend({party:z.union([preferences.party,z.number().int().min(1).max(8).transform(String)]).optional()}).strict(),unsupported:z.boolean().optional()}).strict();
export const restaurantChatSystem=`Interpret dinner preferences for a fictional restaurant booking demo. Return ONLY an object with patch (object) and optionally unsupported (boolean true or false, NEVER null, text or an array). Example JSON {"patch":{"cuisine":"italian","party":"4","day":"tomorrow","seating":"patio","time":"19:00"}}. Include only preferences requested this turn; input restaurant contains current choices. Supported cuisine italian|japanese|mexican; day tonight|tomorrow|weekend; party digit string 1-8; seating indoor|patio (outdoors means patio); time empty or 17:30|18:00|18:30|19:00|19:30|20:00 in 24-hour format (7pm=19:00). Never invent a nearby time or cuisine for an unsupported request. No specific calendar dates, locations or real restaurants supported. Japanese or groups over 4 only have indoor seats; application handles conflicts visibly. Set unsupported true for unsupported requirements and omit those fields; extract any supported preferences. Never confirm a reservation, add stage, ask for personal information, or claim real availability. No names, contact data, URLs, prose or payment fields. Confirmation is a user button in the simulation. /no_think`;
export function restaurantChatDocument(raw:unknown,current=defaultReservation()){
  const {patch,unsupported}=replySchema.parse(raw),before=restaurantSchema.parse(current),next=restaurantSchema.parse(changeReservation(before,patch));
  const note=unsupported?'This demo supports Italian, Japanese or Mexican, 1–8 guests, and the shown days and times. Some requested details are outside the demo. ':'';
  const seatingNote=patch.seating==='patio'&&next.seating!=='patio'?'Patio is unavailable for this selection; inside is shown. ':'';
  return validateDocument(reservationDocument(next,note+seatingNote+reservationReply(before,next,patch.time)));
}
